In [1]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt

In [2]:
def load_file():
    
    df = pd.read_excel('external_regressors_Auto.xlsx')
    df.head()
    df.reset_index(drop=True)
    df = df.set_index('Date')
    df.columns = df.columns.str.replace(' ', '_')
    cols = df.columns
    
    return df, cols

In [3]:
df , cols = load_file()

In [5]:
def load_main_file():
    
    df = pd.read_excel('Model_v2__main.xlsx')
    df.head()
    df.reset_index(drop=True)
    df = df.set_index('Date')
    df.columns = df.columns.str.replace(' ', '_')
    cols = df.columns
    
    return df

In [7]:
df_main = load_main_file()

Forecast_Key  Contact_cust
Date                                 
2017-06-01          STR       72238.0
2017-07-01          STR       72022.0
2017-08-01          STR       76276.0
2017-09-01          STR       73203.0
2017-10-01          STR       75028.0

In [8]:
#from johansen import coint_johansen
from statsmodels.tsa.vector_ar.vecm import coint_johansen

In [9]:
#Extract the unique codes for filtering the over all data    
forecast_group = df.groupby('Forecast_key', as_index=False)
forecast_list = forecast_group.groups.keys()

In [10]:
#Extract the unique codes for filtering the over all data    
target_group = df_main.groupby('Forecast_Key', as_index=False)
target_list = target_group.groups.keys()

In [11]:
for target_item in target_list:
    df3 = df_main[df_main['Forecast_Key'].isin ([target_item])]
    df3=df3.sort_index()
    df5 = df3.Contact_cust

    print('----------------current forecasting targer variable for-----------------------------------------')
    print('--------------------------',target_item,'-------------------------------------------------------')

    for forecast_item in forecast_list:
        print('--------------------------',forecast_item,'-------------------------------------------------------')
        
        df1 = df[df['Forecast_key'].isin ([forecast_item])]
        df1=df1.sort_index()
        df6 = df1.Value_for_forecast_key

        df4 = pd.DataFrame()
        df4['Y'] = df5
        df4['X']  = df6

        df4 = df4.set_index(df3.index)
        model= coint_johansen((df4),1,1)
       # print("\nnormalized eigenvector 0\n", model.evec[:,0] / model.evec[:,0][0])
       # print("\nnormalized eigenvector 1\n", model.evec[:,1] / model.evec[:,1][0])
       # print("\ntest statistics\n", model.lr1[0], model.lr1[1])
        print("\ncritical values\n", model.cvt[0], model.cvt[1])
       # print("\neig\n", model.eig)
       # print("\nevec\n", model.evec)
       # print("\nlr1\n", model.lr1)
       # print("\nlr2\n", model.lr2)
       # print("\ncvt\n", model.cvt)
       # print("\ncvm\n", model.cvm)
       # print("\nind\n", model.ind)
        

----------------current forecasting targer variable for-----------------------------------------
-------------------------- ARM -------------------------------------------------------
-------------------------- 10_years_Treasury -------------------------------------------------------

critical values
 [16.1619 18.3985 23.1485] [2.7055 3.8415 6.6349]
-------------------------- 1_year_Treasury -------------------------------------------------------

critical values
 [16.1619 18.3985 23.1485] [2.7055 3.8415 6.6349]
-------------------------- 30_year_Interest_rate_Mortgage -------------------------------------------------------

critical values
 [16.1619 18.3985 23.1485] [2.7055 3.8415 6.6349]
-------------------------- EMPL_non_farm_Employment -------------------------------------------------------

critical values
 [16.1619 18.3985 23.1485] [2.7055 3.8415 6.6349]
-------------------------- HPI -------------------------------------------------------

critical values
 [16.1619 18.3985 23.1

In [12]:
import statsmodels.tsa.stattools as ts 

In [13]:
for target_item in target_list:
    df3 = df_main[df_main['Forecast_Key'].isin ([target_item])]
    df3=df3.sort_index()
    df5 = df3.Contact_cust
    
    print('----------------current forecasting targer variable for-----------------------------------------')
    print('--------------------------',target_item,'-------------------------------------------------------')

    for forecast_item in forecast_list:
        print('--------------------------',forecast_item,'-------------------------------------------------------')
        
        df1 = df[df['Forecast_key'].isin ([forecast_item])]
        df1=df1.sort_index()
        df6 = df1.Value_for_forecast_key

        df4 = pd.DataFrame()
        df4['Y'] = df5
        df4['X']  = df6

        df4 = df4.set_index(df3.index)
        model= ts.coint(df5, df6)
        print(model)
        


----------------current forecasting targer variable for-----------------------------------------
-------------------------- ARM -------------------------------------------------------
-------------------------- 10_years_Treasury -------------------------------------------------------
(-3.7280258649845326, 0.01685931197536483, array([-4.31395736, -3.55493606, -3.19393252]))
-------------------------- 1_year_Treasury -------------------------------------------------------
(-1.6306985631394708, 0.7077601199540356, array([-4.31395736, -3.55493606, -3.19393252]))
-------------------------- 30_year_Interest_rate_Mortgage -------------------------------------------------------
(-2.6910278603786733, 0.20282215823212718, array([-4.31395736, -3.55493606, -3.19393252]))
-------------------------- EMPL_non_farm_Employment -------------------------------------------------------
(-2.184510437989487, 0.4323649461204469, array([-4.31395736, -3.55493606, -3.19393252]))
-------------------------- HPI --